### ISSUE TITLE
all open windows not shown as selections

### ISSUE THREAD

**Issue by boldcompany** [PKxk8J/click-tab-move#24]
Steps to reproduce:

1. Have multiple Firefox windows open.
2. Right-click and choose "Move."
3. Choose any tab option.
4. Look and see that not all of the open windows are actually listed.

**Comment by PKxk8J** [comment]
The window of the clicked tab is not listed.
Do you mean that there are other not listed windows?

**Comment by boldcompany** [comment]
I think my Firefox installation was corrupted and that was the root issue. When I get time, I'd like to re-test your add-on after cleaning things up.
