### ISSUE TITLE
Request: Multiple tab select

### ISSUE THREAD

**Issue by rayman89** [PKxk8J/click-tab-move#3]
Could you add the option to select more than one tab but less than all the tabs on a window to move to an other window?

**Comment by PKxk8J** [comment]
Thank you for your request.

I think it is possible by selecting tabs in sidebar or popup window.

**Comment by rayman89** [comment]
Thank you for taking it into account and for making the addon in first place.

**Comment by PKxk8J** [comment]
I implemented select window in version 1.1.1.
