### ISSUE TITLE
Move without loading?

### ISSUE THREAD

**Issue by rayman89** [PKxk8J/click-tab-move#7]
Is it possible to move the tabs without loading them? Because If for example there are manny youtube videos there it will be a mess and very resource heavy to move them or to move a lot of any kind of tab to an other window.

**Comment by PKxk8J** [comment]
I think you can avoid loading by focusing the last tab or a not moving tab.

If so, I will implement auto avoidance in the next version.

**Comment by rayman89** [comment]
I tested and yes you can avoid them loading if you focus a tab that you wont move to an other window.

**Comment by PKxk8J** [comment]
I did in version 1.1.2.
